### ISSUE TITLE
How to use other page size like 58mm?

### ISSUE THREAD

**Issue by chenweiyj** [cognitom/paper-css#3]
I am going to print receipt used in supermarket, where its width is 58mm. How can I use this pager-css in self-defined page size?

**Comment by cognitom** [comment]
Hi @chenweiyj,
The paper sizes are defined [here](https://github.com/cognitom/paper-css/blob/master/paper.css#L12-L17) and [here](https://github.com/cognitom/paper-css/blob/master/paper.css#L37-L40).

You can add any paper size like this in your css file:

``` css
body.receipt .sheet { width: 58mm; height: 100mm } /* change height as you like */
@media print { body.receipt { width: 58mm } } /* this line is needed for fixing Chrome's bug */
```

Then HTML file could be like this:

``` html

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>receipt</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.css">
  <link rel="stylesheet" href="../paper.css">
  <style>@page { size: 58mm 100mm }</style>
</head>

<body class="receipt">
  <section class="sheet padding-10mm">
    ...
  </section>
</body>
</html>
```

The point is that we need to set the `size` value in `@page` section, too. Have a fun!
See also: https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size
