### ISSUE TITLE
Page sizes off by one mm?

### ISSUE THREAD

**Issue by rkaravia** [cognitom/paper-css#31]
To me it looks like some page size definitions are off by one mm, e.g. the one for A3:

```css
body.A3               .sheet { width: 297mm; height: 419mm }
body.A3.landscape     .sheet { width: 420mm; height: 296mm }
```

A3 [is defined as 297 x 420 mm](https://en.wikipedia.org/wiki/ISO_216#Dimensions_of_A,_B_and_C_Series), so I would expect it to be like this instead:

```css
body.A3               .sheet { width: 297mm; height: 420mm }
body.A3.landscape     .sheet { width: 420mm; height: 297mm }
```

But maybe there is a reason where some browsers have issues with the "correct" dimensions?
Otherwise I would be happy to submit a PR to adapt them.
