### ISSUE TITLE
Firefox adds a blank page on printing-only  for Firefox 

### ISSUE THREAD

**Issue by Mr-Mohammad** [cognitom/paper-css#34]
Hi
add a blank page on print preview and printing **Firefox** 
When we use A4 paper

**Comment by fgbm** [comment]
Try to increase sheet height like this:

```css
@media print {
    body.A4 .sheet {
        height: 291mm;
    }
}
```
