### ISSUE TITLE
Do i need to credit the author in my work? 

### ISSUE THREAD

**Issue by kq1231** [cognitom/paper-css#44]
I am making notes for myself to study and I am using your paper css which is very nice. it's an amazing piece of work. 
i will distribute my notes to my other classmates but is it necessary for me attribute the name of the author of paper css in my notes due to mit license? I dont want to show any attributions or anything, just the notes themselves.

**Comment by cognitom** [comment]
No, you don't have to. It's ok for me.

Generally speaking, you "should" add a license note somewhere to use any open-source software. But it's enough to just add some comment in the file. At least, you don't have to mention in your main document or report or something.

Maybe, the best way is adding the four lines below (from `/*` to `*/`) on top of `paper.css`:

```css
/*
SPDX-FileCopyrightText: © 2015 Tsutomu Kawamura
SPDX-License-Identifier: MIT
*/

@page { margin: 0 }
body { margin: 0 }
.sheet {
  margin: 0;
  overflow: hidden;
  position: relative;
...
```
